version: '2.1'

services:

  nodeexporter:
    image: prom/node-exporter
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    ports:
      - 9100:9100
    labels:
      org.label-schema.group: "monitoring"

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
    restart: unless-stopped
    ports:
      - 9101:8080
    labels:
      org.label-schema.group: "monitoring"
  


  netdata:
    image: netdata/netdata
    container_name: netdata
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    ports:
      - 9102:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    labels:
      org.label-schema.group: "monitoring"

  # blackexporter:
  #   image: bitnami/blackbox-exporter
  #   container_name: blackexporter
  #   restart: unless-stopped
  #   ports:
  #     - 9103:9115
  #   labels:
  #     org.label-schema.group: "monitoring"

  # portainer:
  #   image: portainer/portainer
  #   ports:
  #   - "9104:9000"
  #   command: -H unix:///var/run/docker.sock
  #   volumes:
  #   - /var/run/docker.sock:/var/run/docker.sock
  #   labels:
  #     org.label-schema.group: "monitoring"